// <auto-generated />
using Komis.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Komis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190306190923_AddOpinion")]
    partial class AddOpinion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Komis.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarDescription");

                    b.Property<string>("EngineCapacity");

                    b.Property<string>("FuelType");

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsCarOfTheWeek");

                    b.Property<bool>("IsInHQ");

                    b.Property<string>("Mark");

                    b.Property<string>("Mileage");

                    b.Property<string>("MiniImageUrl");

                    b.Property<string>("Model");

                    b.Property<string>("Power");

                    b.Property<decimal>("Price");

                    b.Property<int>("ProductionDate");

                    b.HasKey("CarId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Komis.Models.Opinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Message");

                    b.Property<string>("UserName");

                    b.Property<bool>("WaitingForResponse");

                    b.HasKey("Id");

                    b.ToTable("Opinions");
                });
#pragma warning restore 612, 618
        }
    }
}
